# Integrated API Provider Registry Definitive

Executable provider registry for the modern data/API layer.

In [1]:
from pathlib import Path
import sys
import pandas as pd

pd.set_option('display.max_columns', 80)
REPO_ROOT = Path.cwd().resolve().parents[1] if Path.cwd().name == '03_data_providers' else Path.cwd().resolve()
if str(Path.cwd().resolve()) not in sys.path:
    sys.path.insert(0, str(Path.cwd().resolve()))
from api_provider_registry import providers_to_dataframe, credential_status, simple_health_checks, load_dotenv, configure_openbb_from_env
OUTPUT = REPO_ROOT / 'data' / 'data_providers' / 'api_registry'
OUTPUT.mkdir(parents=True, exist_ok=True)
load_dotenv(REPO_ROOT / '.env.local')
load_dotenv(REPO_ROOT / '.env')
providers = providers_to_dataframe()
status = credential_status(mask=True)
health = simple_health_checks(timeout=8)
providers.to_csv(OUTPUT / 'api_providers.csv', index=False)
providers.to_parquet(OUTPUT / 'api_providers.parquet', index=False)
status.to_csv(OUTPUT / 'credential_status_masked.csv', index=False)
health.to_csv(OUTPUT / 'api_provider_health_checks.csv', index=False)
print('OpenBB configured:', configure_openbb_from_env())
display(providers[['name','category','env_var','quality','free_tier']])
display(status)
display(health[['name','reachable','status_code']])

OpenBB configured: {}

,name,category,env_var,quality,free_tier
0,Alpha Vantage,Market Data / Fundamentals,ALPHA_VANTAGE_API_KEY,Media-alta,"Yes, rate-limited"
1,Tiingo,Market Data / News,TIINGO_TOKEN,Alta,"Yes, limited"
2,Financial Modeling Prep,Fundamentals / Market Data,FMP_API_KEY,Media-alta,"Yes, limited"
3,Polygon,Market Data,POLYGON_API_KEY,Alta,"Yes, limited"
4,Intrinio,Fundamentals / Market Data,INTRINIO_API_KEY,Alta,Developer/trial dependent
5,FRED,Macro,FRED_API_KEY,Alta,Yes
6,BLS,Macro / Labor,BLS_API_KEY,Alta,Yes
7,CFTC,Futures / Positioning,CFTC_APP_TOKEN,Alta,Yes
8,Congress.gov,Government / Policy,CONGRESS_GOV_API_KEY,Media-alta,Yes
9,EconDB,Macro,ECONDB_API_KEY,Media-alta,Terms dependent
10,EIA,Energy / Macro,EIA_API_KEY,Alta,Yes
11,Nasdaq Data Link,Market / Alternative / Fundamentals,NASDAQ_API_KEY,Alta,Some free datasets

,name,env_var,configured,credential_preview,openbb_credential
0,Alpha Vantage,ALPHA_VANTAGE_API_KEY,False,,alpha_vantage_api_key
1,Tiingo,TIINGO_TOKEN,False,,tiingo_token
2,Financial Modeling Prep,FMP_API_KEY,False,,fmp_api_key
3,Polygon,POLYGON_API_KEY,False,,polygon_api_key
4,Intrinio,INTRINIO_API_KEY,False,,intrinio_api_key
5,FRED,FRED_API_KEY,False,,fred_api_key
6,BLS,BLS_API_KEY,False,,NaN
7,CFTC,CFTC_APP_TOKEN,False,,NaN
8,Congress.gov,CONGRESS_GOV_API_KEY,False,,NaN
9,EconDB,ECONDB_API_KEY,False,,NaN
10,EIA,EIA_API_KEY,False,,NaN
11,Nasdaq Data Link,NASDAQ_API_KEY,False,,nasdaq_api_key

                       name  reachable  status_code
0             Alpha Vantage       True        200.0
1                    Tiingo       True        200.0
2   Financial Modeling Prep       True        403.0
3                   Polygon       True        200.0
4                  Intrinio       True        200.0
5                      FRED      False          NaN
6                       BLS       True        403.0
7                      CFTC       True        200.0
8              Congress.gov       True        200.0
9                    EconDB       True        200.0
10                      EIA      False          NaN
11         Nasdaq Data Link       True        200.0

Credentials are never stored in this notebook. Use environment variables or ignored `.env.local`.