# Private Active API Services

Local-only smoke checks for active API credentials. Outputs are masked and written to ignored `data/private_api_checks/`.

In [1]:
from pathlib import Path
import sys
import pandas as pd

pd.set_option('display.max_columns', 80)
REPO_ROOT = Path.cwd().resolve().parent if Path.cwd().name == 'data' else Path.cwd().resolve()
PROVIDER_DIR = REPO_ROOT / '02_market_and_fundamental_data' / '03_data_providers'
if str(PROVIDER_DIR) not in sys.path:
    sys.path.insert(0, str(PROVIDER_DIR))
from api_provider_registry import load_dotenv, credential_status, configure_openbb_from_env, active_api_smoke_checks
PRIVATE_DIR = REPO_ROOT / 'data' / 'private_api_checks'
PRIVATE_DIR.mkdir(parents=True, exist_ok=True)
load_summary = {'.env.local': len(load_dotenv(REPO_ROOT / '.env.local')), '.env': len(load_dotenv(REPO_ROOT / '.env'))}
load_summary

{'.env.local': 0, '.env': 0}

In [2]:
status = credential_status(mask=True)
status.to_csv(PRIVATE_DIR / 'credential_status_masked.csv', index=False)
openbb_configured = configure_openbb_from_env()
checks = active_api_smoke_checks(timeout=15)
checks.to_csv(PRIVATE_DIR / 'active_api_smoke_checks.csv', index=False)
checks.to_parquet(PRIVATE_DIR / 'active_api_smoke_checks.parquet', index=False)
display(status)
display(pd.DataFrame([{'openbb_credential': k, 'source_env_var': v} for k, v in sorted(openbb_configured.items())]))
display(checks[['name','configured','ok','status_code','detail']])

,name,env_var,configured,credential_preview,openbb_credential
0,Alpha Vantage,ALPHA_VANTAGE_API_KEY,False,,alpha_vantage_api_key
1,Tiingo,TIINGO_TOKEN,False,,tiingo_token
2,Financial Modeling Prep,FMP_API_KEY,False,,fmp_api_key
3,Polygon,POLYGON_API_KEY,False,,polygon_api_key
4,Intrinio,INTRINIO_API_KEY,False,,intrinio_api_key
5,FRED,FRED_API_KEY,False,,fred_api_key
6,BLS,BLS_API_KEY,False,,NaN
7,CFTC,CFTC_APP_TOKEN,False,,NaN
8,Congress.gov,CONGRESS_GOV_API_KEY,False,,NaN
9,EconDB,ECONDB_API_KEY,False,,NaN
10,EIA,EIA_API_KEY,False,,NaN
11,Nasdaq Data Link,NASDAQ_API_KEY,False,,nasdaq_api_key

Empty DataFrame
Columns: []
Index: []

,name,configured,ok,status_code,detail
0,Alpha Vantage,False,False,NaN,skipped: missing credential
1,Tiingo,False,False,NaN,skipped: missing credential
2,Financial Modeling Prep,False,False,NaN,skipped: missing credential
3,Polygon,False,False,NaN,skipped: missing credential
4,Intrinio,False,False,NaN,skipped: missing credential
5,FRED,False,False,NaN,skipped: missing credential
6,Congress.gov,False,False,NaN,skipped: missing credential
7,EIA,False,False,NaN,skipped: missing credential
8,Nasdaq Data Link,False,False,NaN,skipped: missing credential
9,BLS,False,False,NaN,skipped: missing credential
10,CFTC,False,True,200.0,public endpoint; token optional
11,EconDB,False,False,401.0,skipped: missing credential; endpoint reached

To populate `.env.local` without echoing secrets: `python3.11 data/private_api_activation.py`.